theme="rose_pine_moon_trans"
# theme="catppuccin_macchiato"
# theme = "kanagawa"

[editor]
cursorline = true
auto-format = false
idle-timeout = 0
completion-trigger-len = 1
end-of-line-diagnostics = "hint"
rulers = [80]
bufferline = "always"

[editor.statusline]
left = ["mode", "spinner", "version-control"]
center = ["file-name", "read-only-indicator", "file-modification-indicator"]
right = ["diagnostics", "selections", "register", "position", "position-percentage", "file-encoding", "file-type"]
separator = "|"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-messages = true

[editor.indent-guides]
render = true
character = "▏"
skip-levels = 1

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.soft-wrap]
enable = true

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "warning"

[keys.normal." "]
S-e = "file_explorer"
e = "file_explorer_in_current_buffer_directory"

[keys.normal]
C-q = ":buffer-close"
C-j = ["move_visual_line_down", "scroll_down"]
C-k = ["move_visual_line_up", "scroll_up"]
